spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auction_prod
    username: root
    password: 
    test-on-borrow: true
    validation-query: SELECT 1

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  tomcat:
    access-log-enabled: true
