spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/auction
    username: uat
    password: password

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
