spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.33.10:3306/auction
    username: uat
    password: password
    test-on-borrow: true
    validation-query: SELECT 1

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.springframework: DEBUG

server:
  tomcat:
    access-log-enabled: true
