---
- hosts: default
  sudo: yes
  tasks:

    - name: apache | install perl
      apt: name=libapache2-mod-perl2 state=present

    - name: apache | install apache
      apt: name=apache2 state=present

    - name: apache | link cgid module
      file: src=/etc/apache2/mods-available/{{ item.name }} dest=/etc/apache2/mods-enabled/{{ item.name }} state=link
      with_items:
        - { name: 'cgid.conf' }
        - { name: 'cgid.load' }
      notify:
        - restart apache2

    - name: apache | remove cgi-bin directory
      file: path=/usr/lib/cgi-bin state=absent

    - name: apache | link cgi-bin directory
      file: src=/var/www/cgi-bin dest=/usr/lib/cgi-bin state=link force=yes

    - name: apache | install perl dependency
      apt: name=libjson-perl state=present

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
