---
- hosts: default
  sudo: yes
  tasks:
    - name: mysql | install mysql-server
      apt: name=mysql-server state=present

    - name: mysql | create database
      mysql_db: name=auction state=present

    - name: mysql | add user
      mysql_user: name=uat password=password priv='auction.*:ALL' host=192.168.33.1

    - name: mysql | add localhost user
      mysql_user: name=uat password=password priv='auction.*:ALL'

    - name: mysql | allow remote connections
      lineinfile: dest=/etc/mysql/my.cnf regexp="^bind-address" line="bind-address    = 192.168.33.10"
      notify: restart mysql

  handlers:
    - name: restart mysql
      service: name=mysql state=restarted
